### ISSUE TITLE
mysql Fehler bei Versuch via localhost statt 127.0.0.1 zu verbinden

### ISSUE THREAD

**Issue by mvscheidt** [ctsmedia/docker-baseimage-web#1]
Wenn man in der config für die DB Verbindung localhost angibt, kommt es zu dem unteren Fehler.

Gibt man statt dessen 127.0.0.1 an funktioniert es wieder

```
SQLSTATE[HY000] [2002] No such file or directory

#0 /var/www/share/projektOrdner/htdocs/lib/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect()
#1 /var/www/share/projektOrdner/htdocs/lib/Varien/Db/Adapter/Pdo/Mysql.php(396): Zend_Db_Adapter_Pdo_Mysql->_connect()
#2 /var/www/share/projektOrdner/htdocs/lib/Zend/Db/Adapter/Abstract.php(460): Varien_Db_Adapter_Pdo_Mysql->_connect()
#3 /var/www/share/projektOrdner/htdocs/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SET NAMES utf8', Array)
#4 /var/www/share/projektOrdner/htdocs/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SET NAMES utf8', Array)
#5 /var/www/share/projektOrdner/htdocs/app/code/core/Mage/Core/Model/Resource.php(179): Varien_Db_Adapter_Pdo_Mysql->query('SET NAMES utf8')
#6 /var/www/share/projektOrdner/htdocs/app/code/core/Mage/Core/Model/Resource.php(110): Mage_Core_Model_Resource->_newConnection('pdo_mysql', Object(Mage_Core_Model_Config_Element))
#7 /var/www/share/projektOrdner/htdocs/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php(320): Mage_Core_Model_Resource->getConnection('core_write')
#8 /var/www/share/projektOrdner/htdocs/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php(350): Mage_Core_Model_Resource_Db_Abstract->_getConnection('write')
#9 /var/www/share/projektOrdner/htdocs/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php(335): Mage_Core_Model_Resource_Db_Abstract->_getWriteAdapter()
#10 /var/www/share/projektOrdner/htdocs/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php(360): Mage_Core_Model_Resource_Db_Abstract->_getReadAdapter()
#11 /var/www/share/projektOrdner/htdocs/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(134): Mage_Core_Model_Resource_Db_Abstract->getReadConnection()
#12 /var/www/share/projektOrdner/htdocs/app/code/core/Mage/Core/Model/Config.php(1348): Mage_Core_Model_Resource_Db_Collection_Abstract->__construct(Object(Mage_Core_Model_Resource_Website))
#13 /var/www/share/projektOrdner/htdocs/app/code/core/Mage/Core/Model/Config.php(1380): Mage_Core_Model_Config->getModelInstance('core_resource/w...', Object(Mage_Core_Model_Resource_Website))
#14 /var/www/share/projektOrdner/htdocs/app/Mage.php(499): Mage_Core_Model_Config->getResourceModelInstance('core/website_co...', Object(Mage_Core_Model_Resource_Website))
#15 /var/www/share/projektOrdner/htdocs/app/code/core/Mage/Core/Model/Abstract.php(208): Mage::getResourceModel('core/website_co...', Object(Mage_Core_Model_Resource_Website))
#16 /var/www/share/projektOrdner/htdocs/app/code/core/Mage/Core/Model/Abstract.php(213): Mage_Core_Model_Abstract->getResourceCollection()
#17 /var/www/share/projektOrdner/htdocs/app/code/core/Mage/Core/Model/App.php(619): Mage_Core_Model_Abstract->getCollection()
#18 /var/www/share/projektOrdner/htdocs/app/code/core/Mage/Core/Model/App.php(477): Mage_Core_Model_App->_initStores()
#19 /var/www/share/projektOrdner/htdocs/app/code/core/Mage/Core/Model/App.php(360): Mage_Core_Model_App->_initCurrentStore('', 'store')
#20 /var/www/share/projektOrdner/htdocs/app/Mage.php(692): Mage_Core_Model_App->run(Array)
#21 /var/www/share/projektOrdner/htdocs/index.php(83): Mage::run('', 'store')
#22 {main}
```

**Comment by DanielSchwiperich** [comment]
socket connections and therefore `localhost` should now work

**Comment by mvscheidt** [comment]
Doesnt work for `pdo_mysql.default_socket` - path needs to be updated

Current path for this is `pdo_mysql.default_socket    /tmp/mysql.sock /tmp/mysql.sock`

It does work for `mysql.default_socket` & `mysqli.default_socket`

Path for these is `mysql.default_socket   /var/run/mysqld/mysqld.sock /var/run/mysqld/mysqld.sock`

**Comment by DanielSchwiperich** [comment]
Ok will fix that on the weekend

**Comment by DanielSchwiperich** [comment]
Should now also work for pdo connections. (not tested)
repository is currently being push to registry
